<?xml version="1.0"?>
<!DOCTYPE books [
  <!ELEMENT books (book+)>
  <!ELEMENT book (title, author+, publisher)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT publisher (#PCDATA)>
  <!ATTLIST book isbn CDATA #REQUIRED>
  <!ATTLIST book pubyear CDATA #REQUIRED>
  ]>
<books>
  <book isbn="0201548550" pubyear="1992">
    <author>
      James O. Coplien
    </author>
    <publisher>
      Addison Wesley
    </publisher>
    <title>
      Advanced C++
    </title>
  </book>
  <book isbn="9781430210450" pubyear="2008">
    <author>
      Christopher M. Judd
    </author>
    <author>
      Joseph Faisal Nusairat
    </author>
    <author>
      James Shingler
    </author>
    <publisher>
      Apress
    </publisher>
    <title>
      Beginning Groovy and Grails
    </title>
  </book>
  <book isbn="0201310058" pubyear="2001">
    <author>
      Joshua Bloch
    </author>
    <publisher>
      Addison Wesley
    </publisher>
    <title>
      Effective Java
    </title>
  </book>
</books>
